let
  StartDate = #date(2020,1,1),
  EndDate = #date(2026,12,31),
  Culture = "fr-fr",
  DayCount = Duration.Days(Duration.From(EndDate - StartDate)) + 1,
  Source = List.Dates(StartDate,DayCount,#duration(1,0,0,0)),
  TableFromList = Table.FromList(Source, Splitter.SplitByNothing()),    
  ChangedType = Table.TransformColumnTypes(TableFromList,{{"Column1", type date}}),
  RenamedColumns = Table.RenameColumns(ChangedType,{{"Column1", "Date"}}),
  InsertYear = Table.AddColumn(RenamedColumns, "Year", each Date.Year([Date]), type number),
  InsertMonthKey = Table.AddColumn(InsertYear, "MonthKey", each (([Year] * 100) + Date.Month([Date]))),
  InsertMonth = Table.AddColumn(InsertMonthKey, "Month", each (Number.ToText([Year]) & " - " & Date.ToText([Date], "MMM", Culture)), type text),
  InsertDateKey = Table.AddColumn(InsertMonth, "DateKey", each (([Year] * 10000) + (Date.Month([Date]) * 100) + Date.Day([Date]))),
  InsertDay = Table.AddColumn(InsertDateKey, "Day", each Date.ToText([Date], "yyyy-MM-dd", Culture), type text),
  DateTable = Table.TransformColumnTypes(InsertDay, {{"DateKey", Int64.Type}, {"MonthKey", Int64.Type}})
in
  DateTable
